//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelarusianDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        public System.DateTime Date { get; set; }
        public decimal SummaInTheMorning { get; set; }
        public decimal SummaInTheEvening { get; set; }
    }
}
