//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelarusianDoor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoorsEntities : DbContext
    {
        public DoorsEntities()
            : base("name=DoorsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Balance> Balances { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<IncomeMoney> IncomeMoneys { get; set; }
        public virtual DbSet<OutlayMoney> OutlayMoneys { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
    }
}
