//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelarusianDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeMoney
    {
        public int Id { get; set; }
        public System.DateTime DateIn { get; set; }
        public string Customer { get; set; }
        public decimal? Summa { get; set; }
        public short EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
