//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelarusianDoor
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutlayMoney
    {
        public int Id { get; set; }
        public System.DateTime DateOut { get; set; }
        public string WhereSpend { get; set; }
        public decimal? Summa { get; set; }
        public string WhoReceive { get; set; }
    }
}
